s1={1,2,3}
s={}
ss=set()
print(type(ss))
print(type(s))
print(type(s1))
s2={3,4,5}
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s1.symmetric_difference(s2))
print(s1.issubset(s2))
print(s2.issuperset(s2))
